# Build and run tests inside the docker container
FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /app
# copy the contents of agent working directory on host to workdir in container
COPY . ./
# dotnet commands to build, test, and publish
RUN dotnet restore
RUN dotnet build -c Release
RUN dotnet test -c Release --logger "trx;LogFileName=testresults.trx"
RUN dotnet publish -c Release -o out

CMD ["tail", "-f /dev/null"]
