parameters:
  jobName: false
  environment: false
  registryConnection: false
  kubernetesConnection: false
  namespace: false
  webRepository: false

jobs:
- deployment: "${{ parameters.jobName }}"
  displayName: "Deploy to ${{ parameters.environment }}"
  pool:
    vmImage: 'ubuntu-16.04'
  environment: "${{ parameters.environment }}.${{ parameters.namespace }}"
  variables:
  - group: Release
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: variables
        - script: |
            semVer=$(cat $(Pipeline.Workspace)/variables/semVer)
            echo "##vso[task.setvariable variable=semVer]$semVer"
        - script: |
            echo $(RegistryName)/${{ parameters.webRepository }}:$(semVer)

        - download: current
          artifact: manifests
          
        - task: KubernetesManifest@0
          displayName: Create imagePullSecret
          inputs:
            action: createSecret
            secretName: $(imagePullSecret)
            dockerRegistryEndpoint: ${{ parameters.registryConnection }}
            kubernetesServiceConnection: ${{ parameters.kubernetesConnection }}
            namespace: ${{ parameters.namespace }}
        
        - task: KubernetesManifest@0
          displayName: Deploy to Kubernetes cluster
          inputs:
            action: deploy
            kubernetesServiceConnection: ${{ parameters.kubernetesConnection }}
            namespace: ${{ parameters.namespace }}
            manifests: |
              $(Pipeline.Workspace)/manifests/deployment.yml
              $(Pipeline.Workspace)/manifests/service.yml
            imagePullSecrets: |
              $(imagePullSecret)
            containers: |
              $(RegistryName)/${{ parameters.webRepository }}:$(semVer)