parameters:
  environment: false
  registryConnection: false
  kubernetesConnection: false
  namespace: false
  webRepository: false
  tag: false
  
stages:
- stage: "Deploy${{ parameters.environment }}"
  displayName: "Deploy to ${{ parameters.environment }}"
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-16.04'
    environment: "${{ parameters.environment }}.${{ parameters.namespace }}"
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests
            
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: ${{ parameters.registryConnection }}
              kubernetesServiceConnection: ${{ parameters.kubernetesConnection }}
              namespace: ${{ parameters.namespace }}
          
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: ${{ parameters.kubernetesConnection }}
              namespace: ${{ parameters.namespace }}
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(RegistryName)/${{ parameters.webRepository }}:${{ parameters.tag }}