parameters:
  kubernetesConnection: false
  namespace: false
  
jobs:  
- job: 'setVariable'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: Kubernetes@1
    displayName: Kubernetes login
    inputs:
      connectionType: Kubernetes Service Connection
      kubernetesServiceEndpoint: ${{ parameters.kubernetesConnection }}
      namespace: ${{ parameters.namespace }}
      command: login
  - script: |
      Webservice=$(kubectl get service web -n  ${{ parameters.namespace }} -o json | jq .status.loadBalancer.ingress[0].ip | sed 's/\"//g')
      echo "##vso[task.setvariable variable=WebService;isOutput=true]test"
    name: setWebService